name: flutter_stetho_plus_example
description: Demonstrates how to use the flutter_stetho_plus plugin.

environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_stetho_plus:
    path: ../

flutter:
  uses-material-design: true
