name: flutter_stetho_plus
description: A network inspector for Flutter on Android using the Chrome Dev Tools
version: 0.5.3
homepage: https://github.com/jeffmilanes/flutter_stetho_plus

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.brianegan.flutterstetho
    pluginClass: FlutterStethoPlugin
